<?php

namespace Database\Seeders;

use App\Models\ChiefComplaint;
use Illuminate\Database\Seeder;

class ChiefComplaintSeeder extends Seeder
{
    public function run()
    {
        $complaints = [
            'Sesak napas',
            'Batuk (kering/berdahak)',
            'Nyeri dada saat bernapas',
            'Mengi/napas berbunyi',
            'Pilek/hidung tersumbat',
            'Sakit tenggorokan',
            'Suara serak',
            'Dahak berdarah',
            'Napas pendek',
            'Batuk kronis',
            'Nyeri dada (angin/jantung)',
            'Berdebar-debar',
            'Kaki bengkak',
            'Mudah lelah',
            'Pusing/sakit kepala (tekanan darah tinggi)',
            'Sesak napas saat aktivitas',
            'Pingsan',
            'Jari kebiruan',
            'Nyeri kaki saat berjalan (klaudikasio)',
            'Kedinginan pada ekstremitas',
            'Nyeri perut',
            'Mual',
            'Muntah',
            'Diare',
            'Sembelit',
            'Perut kembung',
            'Sulit menelan',
            'Nyeri ulu hati',
            'Buang air besar berdarah/hitam',
            'Kurang nafsu makan',
            'Berat badan turun',
            'Kuning (ikterik)',
            'Nyeri saat buang air besar',
            'Perut terasa penuh',
            'Sakit kepala',
            'Pusing/vertigo',
            'Kesemutan/baal',
            'Lemah anggota gerak',
            'Kejang',
            'Tremor (getaran)',
            'Gangguan bicara',
            'Gangguan penglihatan (kabur/ganda)',
            'Penurunan kesadaran',
            'Gangguan tidur',
            'Nyeri punggung bawah (LBP)',
            'Nyeri leher',
            'Gangguan keseimbangan',
            'Nyeri sendi',
            'Sendi bengkak',
            'Kekakuan sendi',
            'Nyeri otot',
            'Nyeri tulang',
            'Keterbatasan gerak',
            'Bengkak pada tubuh',
            'Nyeri bahu',
            'Nyeri lutut',
            'Nyeri tumit',
            'Nyeri saat buang air kecil',
            'Sering buang air kecil',
            'Sulit menahan buang air kecil',
            'Buang air kecil berdarah',
            'Nyeri pinggang (ginjal)',
            'Gangguan menstruasi (nyeri/tidak teratur)',
            'Keputihan abnormal',
            'Nyeri panggul',
            'Pembengkakan skrotum',
            'Disfungsi ereksi',
            'Darah pada urine',
            'Gatal-gatal',
            'Ruam/kemerahan kulit',
            'Luka yang tidak sembuh',
            'Perubahan warna kulit',
            'Rambut rontok',
            'Kuku rapuh',
            'Benjolan pada kulit',
            'Bisul',
            'Sering haus',
            'Sering buang air kecil (banyak)',
            'Berat badan naik/turun drastis',
            'Sering lapar',
            'Keringat berlebihan',
            'Intoleransi dingin/panas',
            'Pembengkakan leher (gondok)',
            'Mata merah',
            'Mata berair',
            'Nyeri mata',
            'Penglihatan kabur',
            'Telinga berdenging',
            'Nyeri telinga',
            'Penurunan pendengaran',
            'Mimisan',
            'Demam',
            'Lelah/lemas',
            'Nyeri seluruh tubuh',
            'Sulit tidur',
            'Cemas/depresi',
            'Benjolan di tubuh',
            'Keringat malam',
            'Perdarahan abnormal (misalnya gusi)',
            'Nyeri tidak spesifik',
        ];

        foreach ($complaints as $complaint) {
            ChiefComplaint::create(['name' => $complaint]);
        }
    }
}
